/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_FILES           23
#define MMAP_ASSETS_CHECKSUM        0x7A41

enum MMAP_ASSETS_LISTS {
    MMAP_ASSETS_1_AAF = 0,        /*!< 1.aaf */
    MMAP_ASSETS_ANGRY_AAF = 1,        /*!< angry.aaf */
    MMAP_ASSETS_BLINK_AAF = 2,        /*!< blink.aaf */
    MMAP_ASSETS_BLUEFIRE_AAF = 3,        /*!< bluefire.aaf */
    MMAP_ASSETS_BRAKING_AAF = 4,        /*!< braking.aaf */
    MMAP_ASSETS_DEEPSLEEP_AAF = 5,        /*!< deepsleep.aaf */
    MMAP_ASSETS_DEFAULT_AAF = 6,        /*!< default.aaf */
    MMAP_ASSETS_DIZZY_AAF = 7,        /*!< dizzy.aaf */
    MMAP_ASSETS_FLAG_AAF = 8,        /*!< flag.aaf */
    MMAP_ASSETS_HAPPY_AAF = 9,        /*!< happy.aaf */
    MMAP_ASSETS_INSTALL_AAF = 10,        /*!< install.aaf */
    MMAP_ASSETS_KNOCKING_AAF = 11,        /*!< knocking.aaf */
    MMAP_ASSETS_LOOKLEFT_AAF = 12,        /*!< lookleft.aaf */
    MMAP_ASSETS_LOOKRIGHT_AAF = 13,        /*!< lookright.aaf */
    MMAP_ASSETS_MEMO_AAF = 14,        /*!< memo.aaf */
    MMAP_ASSETS_MUSIC_AAF = 15,        /*!< music.aaf */
    MMAP_ASSETS_SAD_AAF = 16,        /*!< sad.aaf */
    MMAP_ASSETS_SAFEBELT_AAF = 17,        /*!< safebelt.aaf */
    MMAP_ASSETS_SPEEDING_AAF = 18,        /*!< speeding.aaf */
    MMAP_ASSETS_THINKING_AAF = 19,        /*!< thinking.aaf */
    MMAP_ASSETS_UNINSTALL_AAF = 20,        /*!< uninstall.aaf */
    MMAP_ASSETS_WINKING_AAF = 21,        /*!< winking.aaf */
    MMAP_ASSETS_YAWNING_AAF = 22,        /*!< yawning.aaf */
};
